// The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would 
// be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
// What is the value of the first triangle number to have over five hundred divisors?
#include <stdio.h>
#include <math.h>
#define LIMIT 500
// Exhaustive method + Suresh Aggarwal's Mathematics Shortcuts
unsigned short numberOfDivisors(unsigned long long num) {
    unsigned short count    = 0;
    unsigned short divisors = 1;

    for(unsigned long long i = 2; num != 1; i++) {
        while(num % i == 0) count++, num /= i; // num = a ^ m * b ^ n * ...
        divisors *= (count + 1); // num of divisors = (m + 1) * (n + 1) * ...
        count = 0;
    }

    return divisors;
}

unsigned long long divTriangleNum() {
    unsigned long long sum = 1;
    unsigned long long aux = 1;
    unsigned long      inc = 2;

    while(numberOfDivisors(sum) <= LIMIT) sum += inc, inc++;

    return sum;
}

int main() {
    unsigned long long result = divTriangleNum();
    printf("\n%llu\n", result);
    return 0;
}