// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#include <stdio.h>
#include <stdbool.h>

bool is_even(unsigned long num) {
  if(num % 2 == 0)
    return true;
  return false;
}

unsigned long fibo_even_sum(unsigned long limit) {
  unsigned long sum = 0, f1 = 0, f2 = 1;

  while(f2 < limit) {
    if(is_even(f2)) sum += f2;
    f2 = f1 + f2;
    f1 = f2 - f1;
  }

  return sum;
}

int main() {
  printf("%lu\n", fibo_even_sum(4000000));
  return 0;
}
